spring:
  data:
    mongodb:
      uri: mongodb://petya:111@cluster0-shard-00-00-tgncb.mongodb.net:27017,cluster0-shard-00-01-tgncb.mongodb.net:27017,cluster0-shard-00-02-tgncb.mongodb.net:27017/football?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
